server:
  # 服务器的HTTP端口，默认为8080
  port: @server-port@
  servlet:
    # 应用的访问路径
    context-path: @server-servlet-context-path@

cache:
  use-redis: true

spring:
  jackson:
    default-property-inclusion: non_null
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  # redis 配置
  redis:
    # 地址
    host: 192.168.219.2
    # 端口，默认为6379
    port: 6379
    # 密码
    password: purcotton@2019
    database: 8
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms